### ISSUE TITLE
Does not appear in View menu

### ISSUE THREAD

**Issue by AngryRedHerring** [rcrandon/VLC-MediaPlayer-History-Shuffle#1]
I've got it in the right folder, and there are other extensions in that folder that are working, but I can't get this one to appear in the View menu at all.  Tried on two separate machines, one Windows 10, the other Windows 11.

**Comment by rcrandon** [comment]
Should load properly now let me know and I'll close this issue

**Comment by AngryRedHerring** [comment]
Showing up now. Thanks!

**Comment by RadekPilich** [comment]
Doesn't work for me in current version. Is there some additional lua / interface setting necessary?
